# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('mysite', '0009_auto_20171103_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bulletin', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_image', to='filer.Image')),
            ],
        ),
    ]
